version: '3.6'

services:
  zookeeper1:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper1
    ports:
      - 32181:32181
    environment:
        ZOOKEEPER_SERVER_ID: 1
        ZOOKEEPER_CLIENT_PORT: 32181
        ZOOKEEPER_TICK_TIME: 2000
        ZOOKEEPER_INIT_LIMIT: 5
        ZOOKEEPER_SYNC_LIMIT: 2
        ZOOKEEPER_SERVERS: zookeeper1:22888:23888

  kafka1:
    image: confluentinc/cp-kafka:latest
    hostname: kafka1
    ports:
      - 39091:39091
    environment:
      KAFKA_LISTENERS: PLAINTEXT://kafka1:9091,EXTERNAL_LISTENER://kafka1:39091
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9091,EXTERNAL_LISTENER://kafka1:39091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL_LISTENER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:32181
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper1
    
  kafka-schema-registry:
    image: confluentinc/cp-schema-registry:latest
    hostname: schema-registry
    ports:
      - "38083:38083"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL : zookeeper1:32181
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka1:9091
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:38083
    depends_on:
      - zookeeper1